export const DEFAULT_LIMIT: number = 20;

export const DEFAULT_PAGE: number = 1;

export const LIKES_WEIGHT: number = 3;

export const READ_LATER_WEIGHT: number = 1;

export const TRENDING_GRAVITY = 1.8;

export const RESTRICTED_USERNAMES: readonly [string, ...string[]] = [
  "fancanon",
  "vaibhav",
  "admin",
  "administrator",
  "admins",
  "user",
  "users",
  "superuser",
  "mod",
  "moderator",
  "mods",
  "moderators",
  "owner",
  "founder",
  "system",
  "help",
  "support",
  "staff",
  "root",
  "login",
  "logout",
  "signin",
  "signup",
  "register",
  "auth",
  "oauth",
  "session",
  "sessions",
  "account",
  "accounts",
  "password",
  "verify",
  "verification",
  "reset",
  "activate",
  "profile",
  "profiles",
  "me",
  "settings",
  "preferences",
  "notifications",
  "messages",
  "inbox",
  "mail",
  "dashboard",
  "billing",
  "payment",
  "payments",
  "invoice",
  "invoices",
  "subscription",
  "subscriptions",
  "donate",
  "wallet",
  "store",
  "shop",
  "guest",
];
